DEFAULT:
    DEBUG: False

    LANGUAGE_CODE: "pt-br"

    TIME_ZONE: "America/Sao_Paulo"
    USE_I18N: true
    USE_TZ: true

    ROOT_URLCONF: "server.urls"

    WSGI_APPLICATION: "server.wsgi.application"

    ALLOWED_HOSTS: []

    DATABASES:
        "default":
            "ENGINE": "django.db.backends.sqlite3"
            "NAME": "./database/db.sqlite3"

    STATIC_URL: "/static/"
    STATICFILES_DIRS: ["static/"]

    INSTALLED_APPS:
        [
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",

            "apps.polls.apps.PollsConfig",
        ]
    
    MIDDLEWARE:
        [
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
        ]

    TEMPLATES:
        - BACKEND: "django.template.backends.django.DjangoTemplates"
          DIRS: ["templates"]
          APP_DIRS: true
          OPTIONS:
              context_processors:
                  - "django.template.context_processors.debug"
                  - "django.template.context_processors.request"
                  - "django.contrib.auth.context_processors.auth"
                  - "django.contrib.messages.context_processors.messages"

    AUTH_PASSWORD_VALIDATORS:
        [
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        ]

    DEFAULT_AUTO_FIELD: "django.db.models.BigAutoField"

DEVELOPMENT:
    DEBUG: True
    ALLOWED_HOSTS: []

PRODUCTION:
    DEBUG: False
